version: "3"

services:
  db-postgres:
    image: postgres:15
    ports:
      - "5436:5432"
    container_name: "db-postgres"
    restart: always
    volumes:
      - ./banco-de-dado:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase

  app-node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "app-node"
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@db-postgres:5432/mydatabase?schema=public"
    depends_on:
      - db-postgres
    volumes:
      - .:/app
